### ISSUE TITLE
what is <s> and </s> used for? 

### ISSUE THREAD

**Issue by Nutingnon** [leoneversberg/codellama-chatbot#2]
Hi, I am just curious about the effect of `<s>` and `</s>` in your implementation of `ChatModel.py`
as the following part of code:
```python
        # The first user input is _not_ stripped
        do_strip = False
        for old_prompt, old_response in self.history:
            old_prompt = old_prompt.strip() if do_strip else old_prompt
            do_strip = True
            texts.append(f"{old_prompt} [/INST] {old_response.strip()} </s><s>[INST] ")
        user_prompt = user_prompt.strip() if do_strip else user_prompt
        texts.append(f"{user_prompt} [/INST]")
        prompt = "".join(texts)
```

I noticed that the [special tokens in code-llama](https://github.com/meta-llama/codellama/blob/main/llama/generation.py#L321) indicates that `[INST]` and `<<SYS>>` are special tokens, but it does not mention anything about `<s>`. 

I delte the `<s>` and `<\s>` in your code and it seems the code can still correctly work

Can you explain why you add this special tokens at head and tail places?

Thank you very much if you can explain

**Comment by leoneversberg** [comment]
> Hi, I am just curious about the effect of `<s>` and `</s>` in your implementation of `ChatModel.py` as the following part of code:
> 
> ```python
>         # The first user input is _not_ stripped
>         do_strip = False
>         for old_prompt, old_response in self.history:
>             old_prompt = old_prompt.strip() if do_strip else old_prompt
>             do_strip = True
>             texts.append(f"{old_prompt} [/INST] {old_response.strip()} </s><s>[INST] ")
>         user_prompt = user_prompt.strip() if do_strip else user_prompt
>         texts.append(f"{user_prompt} [/INST]")
>         prompt = "".join(texts)
> ```
> 
> I noticed that the [special tokens in code-llama](https://github.com/meta-llama/codellama/blob/main/llama/generation.py#L321) indicates that `[INST]` and `<<SYS>>` are special tokens, but it does not mention anything about `<s>`.
> 
> I delte the `<s>` and `<\s>` in your code and it seems the code can still correctly work
> 
> Can you explain why you add this special tokens at head and tail places?
> 
> Thank you very much if you can explain

I followed the conversational instruction prompt for Code Llama
```
<s>[INST] <<SYS>>
{{ system_prompt }}
<</SYS>>

{{ user_msg_1 }} [/INST] {{ model_answer_1 }} </s><s>[INST] {{ user_msg_2 }} [/INST]
```
See : https://huggingface.co/blog/codellama#conversational-instructions
